# @package _global_

dataset_name: 'ho3d_BB1'

dataset:
  name: 'ho3d'
  root_dir: "/home/cyc/pycharm/lxy/3DGS//HO3D/BB1"
  subject : BB1
  refine: False

  train_view: ['0','1','2', '3']
  val_view: ['4']
  test_view: ['4']
  predict_view: ['4']
  train_sample_rate : 1
  val_sample_rate : 1
  test_sample_rate : 1
  predict_sample_rate : 20


  img_hw:
    - 480
    - 640

white_background: false
data_device: cuda