# @package _global_

dataset_name: 'ho3d'
test_iterations: [0,150000,200000,250000,300000,330000,360000, 400000,430000,4600000,490000,520000]
save_iterations: [490000]

dataset:
  name: 'dexycb'
  root_dir: "/mnt/sda1/lxy/3DGS/DexYCB/"
  refine: False
  finetune: True
  backbone: 'CLIP'
  color_factor: 0
  noise: True
  #test_noise: True

  train_view: [
      'ABF11', 'ABF13', 'ABF10', 'ABF12',
      'BB10', 'BB13', 'BB12', 'BB11',
      'GSF12', 'GSF10', 'GSF13', 'GSF11', 'GPMF11', 'GPMF12', 'GPMF10', 'GPMF13',

      'MC2', 'MC4','MC1', 'MC5',
      'MDF10', 'MDF13', 'MDF11', 'MDF12',

      'ND2',
      'SB10', 'SB12', 'SM2', 'SM3','SM4', 'SS3', 'SS2', 'SS1', 'SMu41', 'SMu40','SMu1',
      'ShSu12', 'ShSu13', 'ShSu10',
      'SiBF10', 'SiBF11', 'SiBF12', 'SiBF13','SiS1',
  ]

  #val_view: []
  _SUBJECTS: [ '0', '1', '2', '3', '4', '5', '6', '7', '8' ]
  _YCB_CLASSES: [ 12, 10, 17, 9, 2, 5, 3, 10, 12, 15, 14 ]
  test_view: [ 'ABF14', 'BB14', 'GSF14', 'GPMF14', 'MC6', 'SM5','ShSu14', 'SiBF14', 'SB14', 'MDF14', 'SMu42' ]

  train_sample_rate : 1
  test_sample_rate : 1

  img_hw:
    - 480
    - 640

white_background: false
data_device: cuda