# @package _global_

dataset_name: 'ho3d'

test_iterations: [60000, 90000,120000,150000,180000, 200000]
save_iterations: [150000, 200000]
checkpoint_iterations: [150000,180000, 200000]

dataset:
  name: 'ho3d'
  root_dir: "/mnt/sda1/lxy/3DGS/HO3D_v3/train/"
  refine: False

  train_view: [
      'ABF12', 'ABF14', 'BB12', 'BB13', 'GPMF12','GPMF14','GSF12','GSF13',
      'MC1', 'MC4', 'MDF12','MDF14', 'ShSu10','ShSu12','SM2','SM4','SMu1','SMu40'
  ]

    #val_view: []
  _SUBJECTS: ['0', '1', '2', '3', '4', '6', '7']
  _YCB_CLASSES: [12, 10, 17, 9, 2, 5, 3, 15, 14]
  #[12, 10, 9, 17, 2, 15, 3, 5, 14]
  test_view: ['ABF12', 'GPMF14','SM2','SMu1'
              ]


  #train_sample_rate : 1
  #test_sample_rate : 1

  img_hw:
    - 480
    - 640

white_background: true
data_device: cuda