# @package _global_

opt:
  iterations: 30000

  lr_ratio: 0.01
  densify_until_iter: 20000
  densification_interval: 200
  densify_from_iter: 1000
  opacity_reset_interval: 2000

  lambda_perceptual: 1e-2

  lambda_nr_xyz: 1e-3
  lambda_nr_scale: 1e-4
  lambda_nr_rot: 1e-4

  lambda_pose_hand: 1e-2
  lambda_pose_obj: 1e-2
  lambda_mano_joint: 100
  lambda_pose_regularization_hand: 1e-1
  lambda_pose_regularization_obj: 1e-1

  lambda_kp_obj_rot: 10
  lambda_kp_obj_trans: 1e4
  lambda_kp_obj_corner: 1e3

  lambda_kp_joint: 1
  lambda_kp_cls: 10

  lambda_kp_verts3d: 1
  lambda_kp_joints3d: 1
  lambda_kp_manopose: 1
  lambda_kp_manoshape: 1

test_interval: -1

model:
  gaussian:
    #delay: 10000
    delay: 0
    #delay: 200000
    until: 200000

  deformer:
    non_rigid:
      pose_correction:
        name: supervise