# @package _global_

opt:
  iterations: 50000

  lr_ratio: 0.0215
  densify_until_iter: 25000
  #densify_until_iter: 45000

  densification_interval: 500

#  feature_lr: 0.001
#  texture_lr: 0.001
#  lr_ratio: 0.001