# @package _global_

opt:
  iterations: 40000

  lr_ratio: 0.1
  densify_until_iter: 35000
  densification_interval: 500

test_interval: -1
test_iterations: [10000,15000,20000,25000,30000,35000,40000]

model:
  gaussian:
    delay: 3000

  deformer:
    non_rigid:
      delay: 8000


#opt:
#  iterations: 15000
#
#  lr_ratio: 0.01
#  densify_until_iter: 10000
#  densification_interval: 200
#
#test_interval: -1